FROM oven/bun:debian

RUN apt-get update -y && \
  apt-get install -y curl python3 && \
  apt-get clean

RUN mkdir -p /home/omp/{.omp,code} \
  && chmod -R 755 /home/omp

WORKDIR /home/omp/code

RUN curl -fsSL https://raw.githubusercontent.com/can1357/oh-my-pi/main/scripts/install.sh | sh
RUN omp install npm:@aliou/pi-guardrails

CMD ["/usr/local/bin/omp"]
